New folder/restaurant/app/urls.py
from django.urls import path
from . import views
from .views import BookingListView, RoomDetailView, CancelBookingView,CheckoutView
urlpatterns = [
    path('',views.home,name='home'),
    path('every/',views.every,name='every'),
    path('gallery/',views.gallery,name='gallery'),
    path('awards/',views.awards,name='awards'),
    path('contact/',views.contact,name='contact'),
    path('carrer/',views.carrer,name='carrer'),
    path('branch1/',views.branch1,name='branch1'),
    path('branch2/',views.branch2,name='branch2'),
    path('service/',views.service,name='service'),
    path('dinning/',views.dinning,name='dinning'),
    path('location/',views.location,name='location'),
    path('contactus/',views.contactus,name='contactus'),
    path('contactus1/',views.contactus1,name='contactus1'),
    path('events/',views.events,name='events'),
    path('meeting/',views.meeting,name='meeting'),
    path('reserve/',views.reserve,name='reserve'),
    path("roomlist/",views.roomlist,name='RoomListView'),
    path('room/<str:category>', RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking_list/', BookingListView.as_view(), name='BookingListView'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(),name='CancelBookingView'),
    path('checkout/', CheckoutView.as_view(), name='CheckoutView'),
    path('success/', views.success_view, name='success_view'),
    path('cancel/', views.cancel_view, name='cancel_view'),
    # path('room/', views.available_rooms, name='available_rooms'),
    # path('book/<int:room_id>/', views.book_room, name='book_room'),
    # # path('booking_confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    # path('rooms/', views.room_list, name='room_list'),
    # path('party-halls/', views.party_hall_list, name='party_hall_list'),
    # path('book/', views.book_room_or_party_hall, name='book_room_or_party_hall'),
    # path('payment/<int:booking_id>/', views.payment, name='payment'),
    # path('confirmation/<int:booking_id>/', views.booking_confirmation, name='confirmation'),
    # path('book/', BookingFormView.as_view(), name='BookingFormView'),
   
    # path('payment/',views.payment,name='payment')
    # path('index/', views.index, name='index'),
    # path('signin/', views.signin, name='signin'),
    # path('signup/', views.signup, name='signup'),
    # path('signout/', views.signout, name='signout'),
    # path('hotel/<uid>',views.get_hotel,name='get_hotel'),
]

New folder/restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path,include
from app import urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urls)),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

New folder/restaurant/app/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.

# class RoomCategory(models.Model):
#     category = models.CharField(max_length=50)
#     rate = models.FloatField()

#     def __str__(self):
#         return self.category


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('DE', 'DELUXE'),
        ('CL', 'CLUB ROOM'),
        ('EX', 'EXECUTIVE SUITE'),
        ('PR', 'PRESIDENTAL '),
        ('AP', 'Apartment'),
    )
    number = models.IntegerField()
    beds = models.IntegerField()
    capacity = models.IntegerField()
    category = models.CharField(max_length=50,choices=ROOM_CATEGORIES)
    rate = models.FloatField()
    def __str__(self):
        return f'{self.number}. Beds = {self.beds} People = {self.capacity}'


class Booking(models.Model):
    PAYMENT_STATUSES = (
        ('COM', 'PAYMENT_COMPLETE'),
        ('INC', 'PAYMENT_INCOMPLETE'),
        ('PAR', 'PAYMENT_PARTIALLY_COMPLETE'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()
    payment_status = models.CharField(max_length=3, choices=PAYMENT_STATUSES)

    def __str__(self):
        return f'From = {self.check_in.strftime("%d-%b-%Y %H:%M")} To = {self.check_out.strftime("%d-%b-%Y %H:%M")}'

    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

# import uuid

# class Room(models.Model):
#     name = models.CharField(max_length=100)
#     description = models.TextField()
#     capacity = models.IntegerField()
#     price_per_hour = models.DecimalField(max_digits=10, decimal_places=2)

#     def __str__(self):
#         return self.name

# class PartyHall(models.Model):
#     name = models.CharField(max_length=100)
#     description = models.TextField()
#     capacity = models.IntegerField()
#     price_per_day = models.DecimalField(max_digits=10, decimal_places=2)

#     def __str__(self):
#         return self.name

# class Booking(models.Model):
#     room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True)
#     party_hall = models.ForeignKey(PartyHall, on_delete=models.CASCADE, null=True, blank=True)
#     customer_name = models.CharField(max_length=100)
#     customer_email = models.EmailField()
#     booking_date = models.DateTimeField(default=timezone.now)
#     duration_in_hours = models.IntegerField()
#     total_price = models.DecimalField(max_digits=10, decimal_places=2)
#     payment_status = models.BooleanField(default=False)  # Payment status: False = Pending, True = Paid

#     def save(self, *args, **kwargs):
#         if self.room:
#             self.total_price = self.room.price_per_hour * self.duration_in_hours
#         elif self.party_hall:
#             self.total_price = self.party_hall.price_per_day
#         super().save(*args, **kwargs)

#     def __str__(self):
#         return f"Booking for {self.customer_name}"


# class BaseModel(models.Model):
#     uid = models.UUIDField(default=uuid.uuid4   , editable=False , primary_key=True)
#     created_at = models.DateField(auto_now_add=True)
#     updated_at = models.DateField(auto_now_add=True)

#     class Meta:
#         abstract = True
#         ordering=['uid']


# class Amenities:
#     amenity_name = models.CharField(max_length=100)

#     def __str__(self):
#         return self.amenity_name

# class Hotel:
#     hotel_name= models.CharField(max_length=100)
#     hotel_price = models.IntegerField()
#     description = models.TextField()
#     # amenities = models.ManyToManyField(Amenities)
#     room_count = models.IntegerField(default=10)

#     def __str__(self) :
#         return self.hotel_name

# class HotelImages:
#     hotel= models.ForeignKey(Hotel ,related_name="images", on_delete=models.CASCADE)
#     images = models.ImageField(upload_to="hotels")


# class HotelBooking:
#     hotel= models.ForeignKey(Hotel  , related_name="hotel_bookings" , on_delete=models.CASCADE)
#     user = models.ForeignKey(User, related_name="user_bookings" , on_delete=models.CASCADE)
#     start_date = models.DateField()
#     end_date = models.DateField()
#     booking_type= models.CharField(max_length=100,choices=(('Pre Paid' , 'Pre Paid') , ('Post Paid' , 'Post Paid')))
    
#     def __str__(self):
#         return f'{self.hotel.hotel_name} {self.start_date} to {self.end_date}'

New folder/restaurant/app/forms.py
from django import forms
from .models import *

from django import forms
from datetime import datetime
from django.core.exceptions import ValidationError
from .models import Room, Person

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M%Z"], widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M%Z"], widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    # room_category = forms.ModelChoiceField(queryset=Room.objects.all())

    # def check_working_hours(self, start, end):
    #     check_in = self.cleaned_data.get('check_in')
    #     check_out = self.cleaned_data.get('check_out')
    #     if not(check_in < start and check_out < end):
    #         raise ValidationError(
    #             "Times beyond working hours, please enter value within working hours")
    #     else:
            # return self.cleaned_data

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

# class BookingForm(forms.ModelForm):
#     class Meta:
#         model = Booking
#         fields = ['customer_name', 'customer_email', 'room',]
#         widgets = {
#             'customer_name': forms.TextInput(attrs={'class': 'form-control'}),
#             'customer_email': forms.EmailInput(attrs={'class': 'form-control'}),
#             'room': forms.Select(attrs={'class': 'form-control'}),
#         }

New folder/restaurant/app/templates/booking/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Cancel</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'css/room_detail_view.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  
    

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="{%static 'images/r1.jpg' %}">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you wanna cancel this Booking? Details-</h2>
                <h3>{{booking.room.number}}{{booking.get_room_category}} {{booking}}</h3>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>

New folder/restaurant/app/templates/booking/booking_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <title>Booking Form</title>
    <link rel="stylesheet" href="{% static 'css/marina_beach_landing.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  
    
  </head>
  <body style="background-color: plum;">
    <div class="d-flex flex-column align-items-center justify-content-center m-3">
      <img src="{% static 'images/logo1.jpg' %}" height="120px" width="120px">
    
    </div>
    <div class="nav container-fluid d-flex flex-column align-items-center justify-content-center">
      
      <h1 id="logo" class="text-center" style="color: #fff;">The Moonlight Resart</h1>
    </div>
    
    <div class="d-flex flex-column align-items-center justify-content-center check_availability">
      <div class="headings m-4">
        <h2>The Moonlight Resart Room Booking</h2>
      </div>

      <div id="search-bar" style="color: #fff;">
        <form method="POST"
          class="search-form m-0 container"
          action="">
          {% csrf_token %}
        <div class="date-row row">
          <div class="form-group d-flex justify-content-space-between col-sm-6 ">
            {{form.check_in.errors}}
            <label class="mr-2" for="{{form.check_in.id_for_label}}">From:</label>
            {{form.check_in}}
          </div>
          <div class="form-group d-flex justify-content-space-around  col-sm-6 ">
            {{form.check_out.errors}}
            <label for="{{form.check_out.id_for_label}}">To: </label>
            {{form.check_out}}
          </div>
        </div>
        <div class="room-row row">
          {{form.room_category.errors}}
          <label for="{{form.room_category.id_for_label}}">Room Category ::</label>
          {{form.room_category}}
        </div>
        <div class="form-group row mw-50 m-2">
          <button class="btn btn-primary col-12  mw-50 " type="submit">Find Room</button>
        </div>
      </form>
    </div>
  </div>
</div>
     <!-- SCRIPTS -->
  <!-- JQuery -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/jquery.min.js' %}"></script> -->
  <!-- Bootstrap tooltips -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/popper.min.js' %}"></script> -->
  <!-- Bootstrap core JavaScript -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/bootstrap.min.js' %}"></script> -->
  <!-- MDB core JavaScript -->
  <!-- <script type="text/javascript" src="{% static 'hotel/js/mdb.min.js' %}"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

New folder/restaurant/app/templates/booking/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/booking_list_view.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  
    
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1 class="d-flex justify-content-center" >Your Bookings</h1>
                <h2 class="d-flex justify-content-center">Welcome dear {{user}}</h2>
            </div>
        </div>

        <div class="bookings">
            {% for booking in booking_list %}
            <div class="booking">
                <img src="{%static 'images/r2.jpg' %}"alt="">
                <div class="category">
                    <h2>{{booking.get_room_category}} Suite</h2>
                </div>
                <div class="from">
                    <h3>From: {{booking.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.check_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{booking.room.beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{booking.room.capacity}}</h3>
                </div>
                <div class="d-flex justify-content-center ">
                    <a href="{% url 'CancelBookingView' booking.pk %}" onclick="return confirm('Are you sure you want to cancel this booking?');"><button class="p-2 m-2 bg-black text-white">Cancel</button></a>
                </div>
            </div>
            {% endfor %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>

New folder/restaurant/app/templates/booking/cancel.html
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

New folder/restaurant/app/templates/booking/checkout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <title>Checkout</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  
    
    <link rel="stylesheet" href="{%static 'css/checkout.css' %}">
  </head>
  <body>
    <div  class="d-flex align-items-center justify-content-center" style="background-color: blueviolet;height: 20vh; width: 100%;">
      <h1 class="text-center text-white">The Moonlight Resart</h1>
    </div>
    <div class="limiter m-3 d-flex align-items-center justify-content-center">
      <div class="container-login100">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-52 p-b-33">
          <form class="signup login100-form validate-form flex-sb flex-w" method="POST" action="">
            {% csrf_token %}
            {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <p class="info m-3">NOTE: You will <strong>NOT</strong> be charged money.&#13;So you can continue and test the app! Cheers &#x1f603; 
            </p>

            <div class="p-t-31 p-b-9 m-2 d-flex align-items-center justify-content-center ">
              <label for="id_name" class="txt1">
                {% trans 'Name' %}
              </label>
              <input class="input100 wrap-input100 validate-input m-2" data-validate = "Name is required" type="text" name="name" placeholder="Name ( Not Required )"  id="id_name">
              <span class="focus-input100"></span>
            </div >
            <div class="p-t-31 p-b-9 m-2 d-flex align-items-center justify-content-center ">
              <label for="id_email" class="txt1" style="display: inline; ">
                {% trans 'Email' %}
              </label>
              <input class="input100 wrap-input100 validate-input m-2" data-validate = "Email is required"  type="email" name="email" placeholder="Email ( Not Required ) "  id="id_email" >
              <span class="focus-input100"></span>
            </div>
    

            <div class="container-login100-form-btn m-t-27 m-2 d-flex align-items-center justify-content-center">
              <button type="submit" class="login100-form-btn p-1">
                {% trans 'Randomize Data and Continue' %}
              </button>
            </div>
          </form>
          <p class="p-t-15 text-center"> P.S. This form generates random data so your data is <strong>NOT</strong> publicly visible! </p>

        </div>
      </div>
    </div>
    
    
    <div id="dropDownSelect1"></div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
  
</html>

New folder/restaurant/app/templates/booking/checkout_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout Confirmation for Hotel Management System</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="{% static 'css/checkout_confirm.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  
    
</head>
<body>
  <div class="container">
    <section class="info">
      <p class="warning"> You will <strong>NOT BE CHARGED</strong> money. But still don't enter actual credit/debit card data </p>
      <h3>Card Number : </h3>
      <h2> 4242 4242 4242 4242 </h2>
      <p>CVV number, name and email can be random.</p>
      <p class="small">(Dummy Data for successful payment)</p>
  </section>
  <section class="booking">
    <div class="booking-details">
      <p>Name: {{person.name}}</p>
      <p>Email: {{person.email}}</p>
      <p>$ {{amount}}</p>
      <p>{{room_name}} Suite</p>
      <p>Check In : {{check_in}}</p>
      <p>Check Out : {{check_out}}</p>
    </div>
      <button id="checkout_btn">Checkout</button>
  </section> 

  </div>
   
   
    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
<script>
    const checkout_id = `{{ checkout_id }}`; //Getting checkout_id from Django context.

    var stripe = Stripe("pk_test_51Hu0AzH60lA1oSooKBHVwQkZ3afq3ST2RISi3oc9G35vFQUQSMUESSorx6Sd700QYz5cY5M3Pyxf9mwZVk1nBPGu00LPxShanC");
    var checkoutButton = document.getElementById("checkout_btn");
    checkoutButton.addEventListener("click", function () { 

      stripe.redirectToCheckout({
        sessionId:`${checkout_id}` //Passing in the checkout_id variable.
      })
      .then(function(result) {
        if (result.error) {
            alert(result.error.message);
          }
      })
      .catch(function (error) {
          console.error("Error:", error);
        })
    });
  </script>
</html>

New folder/restaurant/app/templates/booking/failure.html
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <h1>failed : : {{error}} <a href="mailto:orders@example.com">orders@example.com</a>.</h1>
  </section>
</body>
</html>

New folder/restaurant/app/templates/booking/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">  
    
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

</html>

New folder/restaurant/app/templates/booking/success.html
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <h1>We appreciate your business! If you have any questions, please email<a href="mailto:orders@example.com">orders@example.com</a>.</h1>
  </section>
</body>
</html>